services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Controller
    NetGroup\IconToolkit\Classes\Controller\FetchIconListController:
        tags:
            - 'controller.service_arguments'

    NetGroup\IconToolkit\Classes\Controller\FetchIconStylesController:
        tags:
            - 'controller.service_arguments'

    # Helper
    NetGroup\IconToolkit\Classes\Services\Helper\AssetHelper:
        public: true

    NetGroup\IconToolkit\Classes\Services\Helper\ConfigHelper: ~

    NetGroup\IconToolkit\Classes\Services\Helper\DatabaseHelper: ~

    NetGroup\IconToolkit\Classes\Services\Helper\FileAbstractionHelper: ~

    NetGroup\IconToolkit\Classes\Services\Helper\IconHelper:
        public: true
        arguments:
            $projectDir: '%kernel.project_dir%'

    NetGroup\IconToolkit\Classes\Services\Helper\IconPackConfig: ~

    NetGroup\IconToolkit\Classes\Services\Helper\ScopeHelper:
        public: true
